language: node_js
node_js:
  "node"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - ng serve -prod
script:
  - ng build -prod
  - ng test --watch=false
  - ng e2e
after-success:
  - ng github-pages:deploy --message "travis-ci deployment"
